services:
  ft_onion:
    build: .
    container_name: ft_onion_service
    ports:
      - "4242:4242" 
    volumes:
      - tor_data:/var/lib/tor/hidden_service
    restart: unless-stopped
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  tor_data:
    driver: local
